// ==========================================================================
// 📖 华文智能互动学习阅读器 - 词汇数据库 (data.js)
// ==========================================================================

const lessonTitle = "我的五样";

const lessonData = [
    // ===== 第1段 =====
    ["我", "wǒ", "I", "Saya"],
    ["曾", "céng", "once", "pernah"],
    ["在", "zài", "at", "di"],
    ["一所", "yī suǒ", "a", "sebuah"],
    ["大学", "dà xué", "university", "universiti"],
    ["任教", "rèn jiào", "teach", "mengajar"],
    ["。", "", "", ""],
    ["有一次", "yǒu yī cì", "once", "satu kali"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["给", "gěi", "to", "kepada"],
    ["学生", "xué shēng", "students", "pelajar"],
    ["布置", "bù zhì", "assign", "memberi"],
    ["了", "le", "", ""],
    ["一道", "yī dào", "a", "satu"],
    ["特殊", "tè shū", "special", "khas"],
    ["的", "de", "", ""],
    ["作业", "zuò yè", "assignment", "tugasan"],
    ["：", "", "", ""],
    ["请", "qǐng", "please", "sila"],
    ["在", "zài", "on", "di"],
    ["纸上", "zhǐ shàng", "paper", "atas kertas"],
    ["写下", "xiě xià", "write down", "tulis"],
    ["你", "nǐ", "your", "awak"],
    ["生命", "shēng mìng", "life", "kehidupan"],
    ["中", "zhōng", "in", "dalam"],
    ["最", "zuì", "most", "paling"],
    ["宝贵", "bǎo guì", "precious", "berharga"],
    ["的", "de", "", ""],
    ["五样", "wǔ yàng", "five things", "lima perkara"],
    ["东西", "dōng xi", "things", "benda"],
    ["，", "", "", ""],
    ["并", "bìng", "and", "dan"],
    ["按照", "àn zhào", "according to", "mengikut"],
    ["从", "cóng", "from", "dari"],
    ["次要", "cì yào", "less important", "kurang penting"],
    ["到", "dào", "to", "ke"],
    ["重要", "zhòng yào", "important", "penting"],
    ["的", "de", "", ""],
    ["顺序", "shùn xù", "order", "urutan"],
    ["排列", "pái liè", "arrange", "susun"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第2段

    // ===== 第2段 =====
    ["教室", "jiào shì", "classroom", "bilik darjah"],
    ["里", "lǐ", "in", "di"],
    ["顿时", "dùn shí", "immediately", "segera"],
    ["安静", "ān jìng", "quiet", "senyap"],
    ["下来", "xià lái", "down", "turun"],
    ["，", "", "", ""],
    ["大家", "dà jiā", "everyone", "semua orang"],
    ["都", "dōu", "all", "semua"],
    ["在", "zài", "are", "sedang"],
    ["苦思冥想", "kǔ sī míng xiǎng", "think hard", "berfikir keras"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["也", "yě", "also", "juga"],
    ["坐下来", "zuò xià lái", "sit down", "duduk"],
    ["，", "", "", ""],
    ["在", "zài", "on", "di"],
    ["自己", "zì jǐ", "my own", "sendiri"],
    ["的", "de", "", ""],
    ["纸上", "zhǐ shàng", "paper", "atas kertas"],
    ["写下", "xiě xià", "wrote down", "menulis"],
    ["了", "le", "", ""],
    ["：", "", "", ""],
    ["空气", "kōng qì", "air", "udara"],
    ["、", "", "", ""],
    ["水", "shuǐ", "water", "air"],
    ["、", "", "", ""],
    ["阳光", "yáng guāng", "sunlight", "cahaya matahari"],
    ["、", "", "", ""],
    ["父母", "fù mǔ", "parents", "ibu bapa"],
    ["和", "hé", "and", "dan"],
    ["我", "wǒ", "my", "saya"],
    ["的", "de", "", ""],
    ["孩子", "hái zi", "child", "anak"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第3段

    // ===== 第3段 =====
    ["写下", "xiě xià", "writing down", "menulis"],
    ["这", "zhè", "these", "ini"],
    ["五样", "wǔ yàng", "five things", "lima perkara"],
    ["东西", "dōng xi", "things", "benda"],
    ["并", "bìng", "is", "tidaklah"],
    ["不", "bù", "not", "tidak"],
    ["难", "nán", "difficult", "sukar"],
    ["，", "", "", ""],
    ["难", "nán", "difficult", "sukar"],
    ["的", "de", "", ""],
    ["是", "shì", "is", "ialah"],
    ["接下来", "jiē xià lái", "next", "seterusnya"],
    ["的", "de", "", ""],
    ["环节", "huán jié", "step", "bahagian"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["要求", "yāo qiú", "ask", "meminta"],
    ["学生", "xué shēng", "students", "pelajar"],
    ["们", "men", "", ""],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["现在", "xiàn zài", "now", "sekarang"],
    ["，", "", "", ""],
    ["请", "qǐng", "please", "sila"],
    ["你", "nǐ", "you", "awak"],
    ["在", "zài", "among", "di"],
    ["这", "zhè", "these", "ini"],
    ["五样", "wǔ yàng", "five things", "lima perkara"],
    ["东西", "dōng xi", "things", "benda"],
    ["中", "zhōng", "in", "dalam"],
    ["，", "", "", ""],
    ["划去", "huà qù", "cross out", "potong"],
    ["一样", "yī yàng", "one item", "satu perkara"],
    ["。", "", "", ""],
    ["这", "zhè", "this", "ini"],
    ["意味着", "yì wèi zhe", "means", "bermakna"],
    ["，", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["将", "jiāng", "will", "akan"],
    ["在", "zài", "in", "dalam"],
    ["生命", "shēng mìng", "life", "kehidupan"],
    ["中", "zhōng", "in", "dalam"],
    ["永远", "yǒng yuǎn", "forever", "selamanya"],
    ["失去", "shī qù", "lose", "kehilangan"],
    ["它", "tā", "it", "ia"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第4段

    // ===== 第4段 =====
    ["学生", "xué shēng", "students", "pelajar"],
    ["们", "men", "", ""],
    ["发出", "fā chū", "let out", "mengeluarkan"],
    ["了", "le", "", ""],
    ["惊呼", "jīng hū", "exclamation", "jeritan"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["也", "yě", "also", "juga"],
    ["感到", "gǎn dào", "feel", "merasa"],
    ["一阵", "yī zhèn", "a burst of", "satu"],
    ["揪心", "jiū xīn", "heartache", "perit hati"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["看着", "kàn zhe", "look at", "melihat"],
    ["纸上", "zhǐ shàng", "paper", "atas kertas"],
    ["的", "de", "", ""],
    ["五样", "wǔ yàng", "five things", "lima perkara"],
    ["东西", "dōng xi", "things", "benda"],
    ["，", "", "", ""],
    ["犹豫再三", "yóu yù zài sān", "hesitate again and again", "teragak-agak"],
    ["，", "", "", ""],
    ["最后", "zuì hòu", "finally", "akhirnya"],
    ["划去", "huà qù", "crossed out", "memotong"],
    ["了", "le", "", ""],
    ["“", "", "", ""],
    ["阳光", "yáng guāng", "sunlight", "cahaya matahari"],
    ["”", "", "", ""],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["想", "xiǎng", "think", "fikir"],
    ["，", "", "", ""],
    ["即使", "jí shǐ", "even if", "walaupun"],
    ["没有", "méi yǒu", "without", "tanpa"],
    ["阳光", "yáng guāng", "sunlight", "cahaya matahari"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["还", "hái", "still", "masih"],
    ["可以", "kě yǐ", "can", "boleh"],
    ["生活", "shēng huó", "live", "hidup"],
    ["在", "zài", "in", "di"],
    ["黑暗", "hēi àn", "darkness", "kegelapan"],
    ["中", "zhōng", "in", "dalam"],
    ["，", "", "", ""],
    ["只要", "zhǐ yào", "as long as", "asalkan"],
    ["有", "yǒu", "have", "ada"],
    ["空气", "kōng qì", "air", "udara"],
    ["、", "", "", ""],
    ["水", "shuǐ", "water", "air"],
    ["和", "hé", "and", "dan"],
    ["亲人", "qīn rén", "loved ones", "orang tersayang"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第5段

    // ===== 第5段 =====
    ["“", "", "", ""],
    ["现在", "xiàn zài", "Now", "Sekarang"],
    ["，", "", "", ""],
    ["请", "qǐng", "please", "sila"],
    ["再", "zài", "again", "lagi"],
    ["划去", "huà qù", "cross out", "potong"],
    ["一样", "yī yàng", "one item", "satu perkara"],
    ["。", "", "", ""],
    ["”", "", "", ""],
    ["我", "wǒ", "my", "saya"],
    ["的", "de", "", ""],
    ["声音", "shēng yīn", "voice", "suara"],
    ["有些", "yǒu xiē", "somewhat", "agak"],
    ["颤抖", "chàn dǒu", "trembling", "gemetar"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第6段

    // ===== 第6段 =====
    ["我", "wǒ", "I", "Saya"],
    ["颤抖", "chàn dǒu", "trembling", "gemetar"],
    ["着", "zhe", "", ""],
    ["手", "shǒu", "hand", "tangan"],
    ["，", "", "", ""],
    ["划去", "huà qù", "crossed out", "memotong"],
    ["了", "le", "", ""],
    ["“", "", "", ""],
    ["水", "shuǐ", "water", "air"],
    ["”", "", "", ""],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["想", "xiǎng", "think", "fikir"],
    ["，", "", "", ""],
    ["如果", "rú guǒ", "if", "jika"],
    ["生命", "shēng mìng", "life", "kehidupan"],
    ["即将", "jí jiāng", "about to", "akan"],
    ["终结", "zhōng jié", "end", "berakhir"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["宁愿", "nìng yuàn", "rather", "lebih rela"],
    ["在", "zài", "in", "pada"],
    ["最后", "zuì hòu", "last", "terakhir"],
    ["时刻", "shí kè", "moment", "saat"],
    ["拥抱", "yōng bào", "embrace", "memeluk"],
    ["我", "wǒ", "my", "saya"],
    ["的", "de", "", ""],
    ["亲人", "qīn rén", "loved ones", "orang tersayang"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第7段

    // ===== 第7段 =====
    ["“", "", "", ""],
    ["请", "qǐng", "Please", "Sila"],
    ["再", "zài", "again", "lagi"],
    ["划去", "huà qù", "cross out", "potong"],
    ["一样", "yī yàng", "one item", "satu perkara"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第8段

    // ===== 第8段 =====
    ["这", "zhè", "This", "Kali"],
    ["一次", "yī cì", "time", "ini"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["感到", "gǎn dào", "feel", "merasa"],
    ["一种", "yī zhǒng", "a kind of", "sejenis"],
    ["前所未有", "qián suǒ wèi yǒu", "unprecedented", "tidak pernah berlaku"],
    ["的", "de", "", ""],
    ["绝望", "jué wàng", "despair", "putus asa"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["看着", "kàn zhe", "look at", "melihat"],
    ["“", "", "", ""],
    ["空气", "kōng qì", "air", "udara"],
    ["、", "", "", ""],
    ["父母", "fù mǔ", "parents", "ibu bapa"],
    ["、", "", "", ""],
    ["孩子", "hái zi", "child", "anak"],
    ["”", "", "", ""],
    ["，", "", "", ""],
    ["泪水", "lèi shuǐ", "tears", "air mata"],
    ["模糊", "mó hū", "blurred", "kabur"],
    ["了", "le", "", ""],
    ["双眼", "shuāng yǎn", "eyes", "kedua mata"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["划去", "huà qù", "crossed out", "memotong"],
    ["了", "le", "", ""],
    ["“", "", "", ""],
    ["空气", "kōng qì", "air", "udara"],
    ["”", "", "", ""],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["知道", "zhī dào", "know", "tahu"],
    ["，", "", "", ""],
    ["这", "zhè", "this", "ini"],
    ["意味着", "yì wèi zhe", "means", "bermakna"],
    ["死亡", "sǐ wáng", "death", "kematian"],
    ["，", "", "", ""],
    ["但", "dàn", "but", "tetapi"],
    ["我", "wǒ", "I", "Saya"],
    ["无法", "wú fǎ", "cannot", "tidak dapat"],
    ["在", "zài", "between", "di antara"],
    ["父母", "fù mǔ", "parents", "ibu bapa"],
    ["和", "hé", "and", "dan"],
    ["孩子", "hái zi", "child", "anak"],
    ["之间", "zhī jiān", "between", "antara"],
    ["做出", "zuò chū", "make", "membuat"],
    ["选择", "xuǎn zé", "choice", "pilihan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第9段

    // ===== 第9段 =====
    ["“", "", "", ""],
    ["现在", "xiàn zài", "Now", "Sekarang"],
    ["，", "", "", ""],
    ["只", "zhǐ", "only", "hanya"],
    ["剩下", "shèng xià", "remain", "tinggal"],
    ["最后", "zuì hòu", "last", "terakhir"],
    ["两样", "liǎng yàng", "two items", "dua perkara"],
    ["。", "", "", ""],
    ["请", "qǐng", "please", "sila"],
    ["划去", "huà qù", "cross out", "potong"],
    ["其中", "qí zhōng", "among", "di antaranya"],
    ["一样", "yī yàng", "one item", "satu perkara"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第10段

    // ===== 第10段 =====
    ["教室", "jiào shì", "classroom", "bilik darjah"],
    ["里", "lǐ", "in", "di"],
    ["传来", "chuán lái", "came", "datang"],
    ["了", "le", "", ""],
    ["压抑", "yā yì", "suppressed", "tertahan"],
    ["的", "de", "", ""],
    ["哭声", "kū shēng", "crying", "tangisan"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["看着", "kàn zhe", "look at", "melihat"],
    ["“", "", "", ""],
    ["父母", "fù mǔ", "parents", "ibu bapa"],
    ["”", "", "", ""],
    ["和", "hé", "and", "dan"],
    ["“", "", "", ""],
    ["孩子", "hái zi", "child", "anak"],
    ["”", "", "", ""],
    ["，", "", "", ""],
    ["心如刀割", "xīn rú dāo gē", "heart pierced like a knife", "hati seperti ditikam"],
    ["。", "", "", ""],
    ["最后", "zuì hòu", "finally", "akhirnya"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["划去", "huà qù", "crossed out", "memotong"],
    ["了", "le", "", ""],
    ["“", "", "", ""],
    ["父母", "fù mǔ", "parents", "ibu bapa"],
    ["”", "", "", ""],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["想", "xiǎng", "think", "fikir"],
    ["，", "", "", ""],
    ["父母", "fù mǔ", "parents", "ibu bapa"],
    ["已经", "yǐ jīng", "already", "sudah"],
    ["给", "gěi", "gave", "memberi"],
    ["了", "le", "", ""],
    ["我", "wǒ", "me", "saya"],
    ["生命", "shēng mìng", "life", "kehidupan"],
    ["，", "", "", ""],
    ["而", "ér", "and", "dan"],
    ["孩子", "hái zi", "child", "anak"],
    ["代表", "dài biǎo", "represents", "mewakili"],
    ["着", "zhe", "", ""],
    ["未来", "wèi lái", "future", "masa depan"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["必须", "bì xū", "must", "mesti"],
    ["让", "ràng", "let", "membiarkan"],
    ["生命", "shēng mìng", "life", "kehidupan"],
    ["延续", "yán xù", "continue", "meneruskan"],
    ["下去", "xià qù", "down", "ke bawah"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第11段

    // ===== 第11段 =====
    ["最后", "zuì hòu", "Finally", "Akhirnya"],
    ["，", "", "", ""],
    ["纸上", "zhǐ shàng", "paper", "atas kertas"],
    ["只", "zhǐ", "only", "hanya"],
    ["剩下", "shèng xià", "remain", "tinggal"],
    ["一样", "yī yàng", "one thing", "satu perkara"],
    ["东西", "dōng xi", "thing", "benda"],
    ["：", "", "", ""],
    ["我", "wǒ", "my", "saya"],
    ["的", "de", "", ""],
    ["孩子", "hái zi", "child", "anak"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第12段

    // ===== 第12段 =====
    ["在", "zài", "at", "pada"],
    ["那一刻", "nà yī kè", "that moment", "saat itu"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["突然", "tū rán", "suddenly", "tiba-tiba"],
    ["明白", "míng bái", "understand", "faham"],
    ["了", "le", "", ""],
    ["生命", "shēng mìng", "life", "kehidupan"],
    ["中", "zhōng", "in", "dalam"],
    ["最", "zuì", "most", "paling"],
    ["重要", "zhòng yào", "important", "penting"],
    ["的", "de", "", ""],
    ["东西", "dōng xi", "thing", "benda"],
    ["是", "shì", "is", "ialah"],
    ["什么", "shén me", "what", "apa"],
    ["。", "", "", ""],
    ["我们", "wǒ men", "we", "kita"],
    ["平时", "píng shí", "usually", "biasanya"],
    ["总", "zǒng", "always", "sentiasa"],
    ["觉得", "jué de", "feel", "rasa"],
    ["自己", "zì jǐ", "ourselves", "diri sendiri"],
    ["有", "yǒu", "have", "ada"],
    ["很多", "hěn duō", "many", "banyak"],
    ["追求", "zhuī qiú", "pursuits", "kejaran"],
    ["，", "", "", ""],
    ["有", "yǒu", "have", "ada"],
    ["很多", "hěn duō", "many", "banyak"],
    ["放不下", "fàng bù xià", "cannot let go", "tidak dapat lepaskan"],
    ["的", "de", "", ""],
    ["东西", "dōng xi", "things", "benda"],
    ["，", "", "", ""],
    ["但", "dàn", "but", "tetapi"],
    ["当", "dāng", "when", "apabila"],
    ["生命", "shēng mìng", "life", "kehidupan"],
    ["缩减", "suō jiǎn", "shrink", "mengecil"],
    ["到", "dào", "to", "ke"],
    ["最", "zuì", "most", "paling"],
    ["简练", "jiǎn liàn", "simple", "ringkas"],
    ["的", "de", "", ""],
    ["时刻", "shí kè", "moment", "saat"],
    ["，", "", "", ""],
    ["那", "nà", "those", "itu"],
    ["一层层", "yī céng céng", "layer by layer", "lapisan demi lapisan"],
    ["被", "bèi", "being", "dengan"],
    ["剥落", "bō luò", "peeled off", "terkelupas"],
    ["的", "de", "", ""],
    ["，", "", "", ""],
    ["往往", "wǎng wǎng", "often", "selalunya"],
    ["是", "shì", "are", "ialah"],
    ["那些", "nà xiē", "those", "itu"],
    ["身外之物", "shēn wài zhī wù", "worldly possessions", "harta duniawi"],
    ["。", "", "", ""],
    ["而", "ér", "and", "dan"],
    ["留在", "liú zài", "remain at", "tertinggal di"],
    ["最", "zuì", "most", "paling"],
    ["核心", "hé xīn", "core", "teras"],
    ["位置", "wèi zhì", "position", "kedudukan"],
    ["的", "de", "", ""],
    ["，", "", "", ""],
    ["才", "cái", "then", "barulah"],
    ["是", "shì", "is", "ialah"],
    ["我们", "wǒ men", "our", "kita"],
    ["生命", "shēng mìng", "life", "kehidupan"],
    ["的", "de", "", ""],
    ["真谛", "zhēn dì", "true meaning", "makna sebenar"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第13段

    // ===== 第13段 =====
    ["这次", "zhè cì", "This", "Ini"],
    ["作业", "zuò yè", "assignment", "tugasan"],
    ["不仅", "bù jǐn", "not only", "bukan sahaja"],
    ["让", "ràng", "let", "membuat"],
    ["学生", "xué shēng", "students", "pelajar"],
    ["们", "men", "", ""],
    ["，", "", "", ""],
    ["也", "yě", "also", "juga"],
    ["让", "ràng", "let", "membuat"],
    ["我", "wǒ", "me", "saya"],
    ["自己", "zì jǐ", "myself", "diri sendiri"],
    ["重新", "chóng xīn", "anew", "semula"],
    ["审视", "shěn shì", "examine", "meneliti"],
    ["了", "le", "", ""],
    ["价值观", "jià zhí guān", "values", "nilai"],
    ["。", "", "", ""],
    ["我们", "wǒ men", "We", "Kita"],
    ["要", "yào", "must", "mesti"],
    ["学会", "xué huì", "learn", "belajar"],
    ["珍惜", "zhēn xī", "cherish", "menghargai"],
    ["，", "", "", ""],
    ["学会", "xué huì", "learn", "belajar"],
    ["在", "zài", "in", "dalam"],
    ["纷繁复杂", "fēn fán fù zá", "complex", "rumit"],
    ["的", "de", "", ""],
    ["世界", "shì jiè", "world", "dunia"],
    ["中", "zhōng", "in", "dalam"],
    ["，", "", "", ""],
    ["守住", "shǒu zhù", "hold on to", "mempertahankan"],
    ["那些", "nà xiē", "those", "itu"],
    ["最", "zuì", "most", "paling"],
    ["核心", "hé xīn", "core", "teras"],
    ["、", "", "", ""],
    ["最", "zuì", "most", "paling"],
    ["宝贵", "bǎo guì", "precious", "berharga"],
    ["的", "de", "", ""],
    ["东西", "dōng xi", "things", "benda"],
    ["。", "", "", ""],
];

// 如果使用模块导出，取消下一行注释；若通过 script 标签引入，则全局可用
// export { lessonTitle, lessonData };
